### ISSUE TITLE
大佬帮忙看下这个报错

### ISSUE THREAD

**Issue by Suelence-hu** [Shudeng/GPAttack#1]
![image](https://user-images.githubusercontent.com/39931365/92135042-da87c200-ee3c-11ea-9f2a-3b75d23ca6cb.png)
这个该如何解决呢

**Comment by Shudeng** [comment]
你好，这个可能是由于 pytorch 版本不一样。我本地的版本是：
![image](https://user-images.githubusercontent.com/22614443/92188896-637c1900-ee90-11ea-86ce-66c8a5c77ffe.png)

希望这个 https://github.com/pytorch/pytorch/issues/33988 能解决你的问题。
