### ISSUE TITLE
关于yolov4_helper.py单文件运行的问题

### ISSUE THREAD

**Issue by Zengyf-CVer** [Shudeng/GPAttack#4]
@Shudeng  @Wu-Shudeng 
你好，我单独运行了yolov4_helper.py这个文件，发现了一个关于device的报错：
![ksnip_20211010-131134](https://user-images.githubusercontent.com/41098760/136683165-40dd5716-144f-4783-bd24-3c3ec90f9c1b.png)

请问这个怎么解决？

**Comment by Shudeng** [comment]
你可以试试把所有tensor 放在一个 device 上面，比如：
```python
new_img, img = new_img.to("cuda:0"), img.to("cuda:0")
new_img[:,:,0] = new_img[:,:,0]+img[:,:,2]
new_img[:,:,1] = new_img[:,:,1]+img[:,:,1]
new_img[:,:,2] = new_img[:,:,2]+img[:,:,0]
```

**Comment by yihui8776** [comment]
可以将img也转   img.to_device()

**Comment by yihui8776** [comment]
可以将img转cuda
img[:,:,2].to(device)
